import { CardDef } from "./types";

// Reihenfolge der Zeitbonus-Karten entspricht SizeConfig.timeBonusMinutes[index].
export const CARD_LIBRARY: CardDef[] = [
  // -------------------------------------------------------------- TIME_BONUS
  {
    id: "tb_small",
    name: "Kurzer Vorsprung",
    type: "TIME_BONUS",
    rarity: "COMMON",
    effectKey: "TIME_BONUS_0",
    target: "SELF",
    duration: "Sofort, zählt am Rundenende",
    activationCondition: "Jederzeit spielbar",
    timing: "END_OF_ROUND",
    stackable: true,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Addiert einen kleinen Zeitbonus zur finalen Versteckzeit.",
    honorSystem: false,
    scalesBySize: true,
  },
  {
    id: "tb_medium",
    name: "Guter Vorsprung",
    type: "TIME_BONUS",
    rarity: "COMMON",
    effectKey: "TIME_BONUS_1",
    target: "SELF",
    duration: "Sofort, zählt am Rundenende",
    activationCondition: "Jederzeit spielbar",
    timing: "END_OF_ROUND",
    stackable: true,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Addiert einen soliden Zeitbonus zur finalen Versteckzeit.",
    honorSystem: false,
    scalesBySize: true,
  },
  {
    id: "tb_large",
    name: "Starker Vorsprung",
    type: "TIME_BONUS",
    rarity: "UNCOMMON",
    effectKey: "TIME_BONUS_2",
    target: "SELF",
    duration: "Sofort, zählt am Rundenende",
    activationCondition: "Jederzeit spielbar",
    timing: "END_OF_ROUND",
    stackable: true,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Addiert einen starken Zeitbonus zur finalen Versteckzeit.",
    honorSystem: false,
    scalesBySize: true,
  },
  {
    id: "tb_huge",
    name: "Grosser Zeitgewinn",
    type: "TIME_BONUS",
    rarity: "RARE",
    effectKey: "TIME_BONUS_3",
    target: "SELF",
    duration: "Sofort, zählt am Rundenende",
    activationCondition: "Jederzeit spielbar",
    timing: "END_OF_ROUND",
    stackable: true,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Addiert einen grossen Zeitbonus zur finalen Versteckzeit.",
    honorSystem: false,
    scalesBySize: true,
  },
  {
    id: "tb_jackpot",
    name: "Jackpot-Zeit",
    type: "TIME_BONUS",
    rarity: "LEGENDARY",
    effectKey: "TIME_BONUS_4",
    target: "SELF",
    duration: "Sofort, zählt am Rundenende",
    activationCondition: "Jederzeit spielbar",
    timing: "END_OF_ROUND",
    stackable: true,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Der grösstmögliche Zeitbonus im Spiel.",
    honorSystem: false,
    scalesBySize: true,
  },

  // ----------------------------------------------------------------- POWERUP
  {
    id: "pu_hand_size",
    name: "Erweiterte Hand",
    type: "POWERUP",
    rarity: "UNCOMMON",
    effectKey: "HAND_SIZE_INCREASE",
    target: "SELF",
    duration: "Rest der Runde",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Erhöht das Handkartenlimit dauerhaft um 2 für den Rest der Runde.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "pu_extra_info",
    name: "Insiderwissen",
    type: "POWERUP",
    rarity: "COMMON",
    effectKey: "EXTRA_INFO_NEXT_DRAW",
    target: "SELF",
    duration: "Nächste beantwortete Frage",
    activationCondition: "Jederzeit spielbar, vor Beantwortung einer Frage",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Bei der nächsten beantworteten Frage ziehst du eine zusätzliche Karte, bevor du auswählst, welche du behältst.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "pu_question_manipulation",
    name: "Fragenverzerrung",
    type: "POWERUP",
    rarity: "RARE",
    effectKey: "VOID_NEXT_QUESTION",
    target: "SELF",
    duration: "Nächste gestellte Frage",
    activationCondition: "Muss gespielt werden, bevor die Frist einer offenen Frage abläuft",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Annulliert die nächste gestellte Frage: Sie gilt als nicht gestellt, es werden keine Karten gezogen. Der Wiederholungspreis der Frage bleibt unverändert.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "pu_mobility",
    name: "Bewegungsfreiheit",
    type: "POWERUP",
    rarity: "UNCOMMON",
    effectKey: "MOBILITY",
    target: "SELF",
    duration: "Bis zur Rückkehr, vor Beginn des Endgames",
    activationCondition: "Nur während der Seeking Period, vor dem Endgame",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Du darfst dich einmalig bis zu 1 km ausserhalb deiner Hiding Zone bewegen und musst vor Beginn des Endgames zurück sein. Ehrenregel - nicht technisch erzwungen.",
    honorSystem: true,
    scalesBySize: false,
  },
  {
    id: "pu_defensive",
    name: "Schutzschild",
    type: "POWERUP",
    rarity: "UNCOMMON",
    effectKey: "FORCE_STRONG_NEXT_QUESTION",
    target: "SELF",
    duration: "Nächste gestellte Frage",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die nächste gestellte Frage kostet die Seeker automatisch den vollen (starken) Preis, unabhängig davon, welche Variante sie gewählt haben.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "pu_time_multiplier",
    name: "Zeitverstärker",
    type: "POWERUP",
    rarity: "RARE",
    effectKey: "DOUBLE_NEXT_TIME_BONUS",
    target: "SELF",
    duration: "Nächste gespielte Zeitbonus-Karte",
    activationCondition: "Muss vor der Zeitbonus-Karte gespielt werden",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Der nächste Zeitbonus, den du spielst, zählt doppelt.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "pu_card_draw",
    name: "Nachschub",
    type: "POWERUP",
    rarity: "COMMON",
    effectKey: "INSTANT_DRAW_2_KEEP_1",
    target: "SELF",
    duration: "Sofort",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: true,
    discardAfterUse: true,
    counterable: false,
    textDescription: "Ziehe sofort 2 Karten und behalte 1 davon.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "pu_question_block",
    name: "Maulkorb",
    type: "POWERUP",
    rarity: "RARE",
    effectKey: "BLOCK_CATEGORY",
    target: "SEEKERS",
    duration: "15/30/45 Min. je nach Spielgrösse",
    activationCondition: "Jederzeit spielbar, Kategorie wird beim Spielen gewählt",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Sperrt eine frei gewählte Fragekategorie für die Seeker für eine begrenzte Zeit. Fragen dieser Kategorie können währenddessen nicht gestellt werden.",
    honorSystem: false,
    scalesBySize: true,
  },

  // ------------------------------------------------------------------- CURSE
  {
    id: "curse_detour",
    name: "Umweg-Fluch",
    type: "CURSE",
    rarity: "COMMON",
    effectKey: "TRAVEL_DETOUR",
    target: "SEEKERS",
    duration: "Nächste Fahrt",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Bei ihrer nächsten Fahrt müssen die Seeker mindestens einmal umsteigen, falls eine direkte Verbindung existiert. Ehrenregel.",
    honorSystem: true,
    scalesBySize: false,
  },
  {
    id: "curse_forbidden_transport",
    name: "Verbotenes Verkehrsmittel",
    type: "CURSE",
    rarity: "UNCOMMON",
    effectKey: "FORBID_TRANSPORT_MODE",
    target: "SEEKERS",
    duration: "30 Minuten",
    activationCondition: "Jederzeit spielbar, Verkehrsmittel wird beim Spielen gewählt",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Ein gewähltes Verkehrsmittel (Zug/Bus/Tram/Schiff) darf für 30 Minuten nicht bestiegen werden. Ehrenregel.",
    honorSystem: true,
    scalesBySize: false,
  },
  {
    id: "curse_expensive_question",
    name: "Teuer Erkauft",
    type: "CURSE",
    rarity: "UNCOMMON",
    effectKey: "NEXT_QUESTION_DOUBLE_COST",
    target: "SEEKERS",
    duration: "Nächste gestellte Frage",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die nächste gestellte Frage kostet automatisch den doppelten Kartenpreis, unabhängig von ihrer Wiederholungshistorie.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "curse_conditional_question",
    name: "Bedingungsfrage",
    type: "CURSE",
    rarity: "RARE",
    effectKey: "GATE_NEXT_QUESTION_PHOTO",
    target: "SEEKERS",
    duration: "Bis erledigt",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Bevor die Seeker die nächste Frage stellen dürfen, müssen sie ein Foto ihres aktuellen Standorts einreichen.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "curse_time_thief",
    name: "Zeitdieb",
    type: "CURSE",
    rarity: "UNCOMMON",
    effectKey: "SEEKER_TIME_FREEZE",
    target: "SEEKERS",
    duration: "10/15/20 Min. je nach Spielgrösse",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die Seeker dürfen für eine begrenzte Zeit nicht weiterreisen oder den Standort wechseln. Ein Timer läuft sichtbar herunter. Ehrenregel - nicht technisch erzwungen.",
    honorSystem: true,
    scalesBySize: true,
  },
  {
    id: "curse_forced_pause",
    name: "Zwangspause",
    type: "CURSE",
    rarity: "COMMON",
    effectKey: "SEEKER_BOARDING_FREEZE",
    target: "SEEKERS",
    duration: "5/10/15 Min. je nach Spielgrösse",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die Seeker dürfen für eine begrenzte Zeit in kein neues Verkehrsmittel einsteigen.",
    honorSystem: true,
    scalesBySize: true,
  },
  {
    id: "curse_physical_challenge",
    name: "Sportliche Herausforderung",
    type: "CURSE",
    rarity: "COMMON",
    effectKey: "REQUIRE_WALK_CONFIRM",
    target: "SEEKERS",
    duration: "Bis erledigt",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die Seeker müssen 500 m zu Fuss zurücklegen, bevor sie weitersuchen dürfen (per Ehrlichkeit bestätigt).",
    honorSystem: true,
    scalesBySize: false,
  },
  {
    id: "curse_proof_photo",
    name: "Beweisfoto-Aufgabe",
    type: "CURSE",
    rarity: "COMMON",
    effectKey: "REQUIRE_SEEKER_PHOTO",
    target: "SEEKERS",
    duration: "Bis erledigt",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die Seeker müssen ein Foto eines markanten Objekts ihrer aktuellen Umgebung hochladen, bevor sie fortfahren dürfen.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "curse_delayed_answer",
    name: "Nachrichtenverzug",
    type: "CURSE",
    rarity: "RARE",
    effectKey: "DELAY_NEXT_ANSWER_REVEAL",
    target: "SEEKERS",
    duration: "10 Minuten nach Erhalt der Antwort",
    activationCondition: "Muss gespielt werden, bevor die Frage beantwortet ist",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Die Antwort auf die nächste Frage wird den Seekern erst 10 Minuten nach Eingang der Antwort angezeigt.",
    honorSystem: false,
    scalesBySize: false,
  },
  {
    id: "curse_source_lock",
    name: "Quellensperre",
    type: "CURSE",
    rarity: "LEGENDARY",
    effectKey: "BLOCK_ALL_QUESTIONS",
    target: "SEEKERS",
    duration: "20 Minuten",
    activationCondition: "Jederzeit spielbar",
    timing: "IMMEDIATE",
    stackable: false,
    discardAfterUse: true,
    counterable: false,
    textDescription:
      "Alle Fragekategorien sind für 20 Minuten komplett gesperrt. Die stärkste Curse im Spiel.",
    honorSystem: false,
    scalesBySize: false,
  },
];

export const CARD_BY_ID = new Map(CARD_LIBRARY.map((c) => [c.id, c]));

export const RARITY_WEIGHTS: Record<string, number> = {
  COMMON: 42,
  UNCOMMON: 30,
  RARE: 19,
  LEGENDARY: 9,
};

export const TIME_BONUS_CARD_ORDER = [
  "tb_small",
  "tb_medium",
  "tb_large",
  "tb_huge",
  "tb_jackpot",
];
